server:
  port: 9099

spring:
  messages:
    encoding: UTF-8
  thymeleaf:
    encoding: UTF-8


springdoc:
  api-docs:
    path: /api-docs

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG

### actuator 관련 설정 (메트릭 엔드포인트)
### localhost:9099/actuator/prometheus
management:
  endpoints:
    web:
      exposure:
        include: metrics, prometheus